import { useEffect, useRef } from 'react';
import { useLocation } from 'react-router-dom';
import { useUILanguage } from '../context/UILanguageContext';
import { translateMany } from '../utils/autoTranslate';

const SKIP_TAGS = new Set([
  'SCRIPT',
  'STYLE',
  'NOSCRIPT',
  'TEXTAREA',
  'CODE',
  'PRE',
]);

// Text must contain at least one letter (Latin / accented Latin / CJK) to be
// worth translating — pure numbers and punctuation are skipped.
const HAS_LETTER = /[A-Za-zÀ-ɏ一-鿿]/;

export default function PageTranslator() {
  const { uiLang } = useUILanguage();
  const location = useLocation();
  // Stores the original (untranslated) text for every text node we touch.
  const originals = useRef(new WeakMap<Text, string>());

  useEffect(() => {
    let cancelled = false;
    let debounceTimer: ReturnType<typeof setTimeout> | undefined;

    const observer = new MutationObserver((mutations) => {
      const hasContentChange = mutations.some(
        (m) =>
          (m.type === 'childList' && m.addedNodes.length > 0) ||
          m.type === 'characterData'
      );
      if (!hasContentChange) return;
      if (debounceTimer) clearTimeout(debounceTimer);
      debounceTimer = setTimeout(run, 350);
    });

    function collectTextNodes(): Text[] {
      const walker = document.createTreeWalker(
        document.body,
        NodeFilter.SHOW_TEXT,
        {
          acceptNode(node) {
            const text = node.nodeValue ?? '';
            if (!text.trim() || !HAS_LETTER.test(text)) {
              return NodeFilter.FILTER_REJECT;
            }
            const parent = (node as Text).parentElement;
            if (!parent) return NodeFilter.FILTER_REJECT;
            if (SKIP_TAGS.has(parent.tagName)) return NodeFilter.FILTER_REJECT;
            if (parent.closest('.notranslate')) return NodeFilter.FILTER_REJECT;
            return NodeFilter.FILTER_ACCEPT;
          },
        }
      );
      const nodes: Text[] = [];
      let current: Node | null;
      while ((current = walker.nextNode())) {
        nodes.push(current as Text);
      }
      return nodes;
    }

    async function run() {
      const nodes = collectTextNodes();
      const items = nodes.map((node) => {
        let original = originals.current.get(node);
        if (original === undefined) {
          original = node.nodeValue ?? '';
          originals.current.set(node, original);
        }
        return { node, original };
      });

      const texts = items
        .map((it) => it.original.trim())
        .filter((t) => t.length > 0);
      if (texts.length === 0) return;

      const translations = await translateMany(texts, uiLang);
      if (cancelled) return;

      // Pause observation while we mutate the DOM so our own writes do not
      // trigger another translation pass.
      observer.disconnect();
      for (const { node, original } of items) {
        const trimmed = original.trim();
        const translated = translations.get(trimmed);
        if (!translated) continue;
        const lead = original.match(/^\s*/)?.[0] ?? '';
        const trail = original.match(/\s*$/)?.[0] ?? '';
        const next = lead + translated + trail;
        if (node.nodeValue !== next) node.nodeValue = next;
      }
      if (!cancelled) {
        // Reconnect on the next macrotask, after the MutationObserver has
        // discarded the records generated by our own writes.
        setTimeout(() => {
          if (!cancelled) {
            observer.observe(document.body, {
              childList: true,
              subtree: true,
              characterData: true,
            });
          }
        }, 0);
      }
    }

    run();
    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: true,
    });

    return () => {
      cancelled = true;
      if (debounceTimer) clearTimeout(debounceTimer);
      observer.disconnect();
    };
  }, [uiLang, location.pathname]);

  return null;
}
